/**
 * @file default_raster_mod.h
 * @copyright Copyright (c) 2021, Southwest Research Institute
 *
 * @par License
 * Software License Agreement (Apache License)
 * @par
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * @par
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <noether_tpp/core/tool_path_modifier.h>
#include <noether_tpp/core/types.h>

namespace noether_tpp
{

/**
 * @brief The DefaultRasterMod class - a modifier that enforces the definition of a raster path on
 * the path generated by a RasterPlanner.  It will enforce uniform waypoint orientation, uniform
 * raster direction, and consistent raster ordering.
 */
class DefaultRasterMod : public OneTimeToolPathModifier
{
public:
  ToolPaths modify(ToolPaths toolpaths) override;
};

} // namespace noether_tpp
