#goal definition - Input Mesh
pcl_msgs/PolygonMesh input_mesh

noether_msgs/SegmentationConfig segmentation_config
noether_msgs/FilteringConfig filtering_config
---
#result definition - Output Meshes
pcl_msgs/PolygonMesh[] output_mesh

---
#feedback - Some sort of percentage or partial meshes?

